name: CD

on:
  push:
    paths-ignore:
    - '.github/**'
    - '**/readme.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      #with:
      #  fetch-depth: 1
    - uses: mavrosxristoforos/jxb@master
      with:
        build-file: 'build_ns.jxb'
        ignore-inc-version: true
