name: CD

on:
  push:
    paths-ignore:
    - '.github/**'
    - '.git**'
    - '**README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Joomla Package
      id: jxbuild
      uses: mavrosxristoforos/jxb@master
      with:
        build-file: 'build_ns.jxb'
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@master
      with:
        xml-file: 'pkg_ns.xml'
        xpath: '//version'
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.getxml.outputs.info }}
        release_name: Newsletter Subscriber ${{ steps.getxml.outputs.info }}
        #body: |
        #    Changes in this Release
        #    - First Change
        #    - Second Change
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pkg_ns.zip
        asset_name: pkg_ns.zip
        asset_content_type: application/zip          
    #- name: Create Release
    #  uses: ncipollo/release-action@v1
    #  with:
    #    artifacts: 'pkg_ns.zip'
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    tag: ${{ steps.getxml.outputs.info }}
